# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.runs/synth_1/architecture1.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param netlist.enableMultipleFileLines 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7v2000tflg1925-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.cache/wt [current_project]
set_property parent.project_path C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/conv_pkg.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/architecture1_entity_declarations.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/xlclockdriver_rd.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/single_reg_w_init.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/srl33e.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/synth_reg.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/synth_reg_reg.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/synth_reg_w_init.vhd
  C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/imports/sysgen/architecture1.vhd
}
read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i2/architecture1_c_addsub_v12_0_i2.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i1/architecture1_c_addsub_v12_0_i1.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i3/architecture1_c_addsub_v12_0_i3.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i0/architecture1_c_addsub_v12_0_i0.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i19/architecture1_c_addsub_v12_0_i19.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i18/architecture1_c_addsub_v12_0_i18.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i20/architecture1_c_addsub_v12_0_i20.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i21/architecture1_c_addsub_v12_0_i21.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i22/architecture1_c_addsub_v12_0_i22.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i17/architecture1_c_addsub_v12_0_i17.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i4/architecture1_c_addsub_v12_0_i4.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i9/architecture1_c_addsub_v12_0_i9.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i10/architecture1_c_addsub_v12_0_i10.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i5/architecture1_c_addsub_v12_0_i5.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i6/architecture1_c_addsub_v12_0_i6.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i8/architecture1_c_addsub_v12_0_i8.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i7/architecture1_c_addsub_v12_0_i7.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i113/architecture1_mult_gen_v12_0_i113.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i115/architecture1_mult_gen_v12_0_i115.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i109/architecture1_mult_gen_v12_0_i109.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i111/architecture1_mult_gen_v12_0_i111.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i117/architecture1_mult_gen_v12_0_i117.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i104/architecture1_mult_gen_v12_0_i104.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i107/architecture1_mult_gen_v12_0_i107.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i116/architecture1_mult_gen_v12_0_i116.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i118/architecture1_mult_gen_v12_0_i118.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i106/architecture1_mult_gen_v12_0_i106.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i108/architecture1_mult_gen_v12_0_i108.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i119/architecture1_mult_gen_v12_0_i119.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i112/architecture1_mult_gen_v12_0_i112.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i114/architecture1_mult_gen_v12_0_i114.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i120/architecture1_mult_gen_v12_0_i120.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i105/architecture1_mult_gen_v12_0_i105.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i110/architecture1_mult_gen_v12_0_i110.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i11/architecture1_c_addsub_v12_0_i11.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i15/architecture1_c_addsub_v12_0_i15.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i16/architecture1_c_addsub_v12_0_i16.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i14/architecture1_c_addsub_v12_0_i14.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i13/architecture1_c_addsub_v12_0_i13.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i12/architecture1_c_addsub_v12_0_i12.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i27/architecture1_c_addsub_v12_0_i27.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i28/architecture1_c_addsub_v12_0_i28.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i25/architecture1_c_addsub_v12_0_i25.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i23/architecture1_c_addsub_v12_0_i23.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i24/architecture1_c_addsub_v12_0_i24.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i26/architecture1_c_addsub_v12_0_i26.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i4/architecture1_mult_gen_v12_0_i4.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i32/architecture1_c_addsub_v12_0_i32.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i29/architecture1_c_addsub_v12_0_i29.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i30/architecture1_c_addsub_v12_0_i30.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i33/architecture1_c_addsub_v12_0_i33.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i35/architecture1_c_addsub_v12_0_i35.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i2/architecture1_mult_gen_v12_0_i2.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i34/architecture1_c_addsub_v12_0_i34.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_c_addsub_v12_0_i31/architecture1_c_addsub_v12_0_i31.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i1/architecture1_mult_gen_v12_0_i1.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i3/architecture1_mult_gen_v12_0_i3.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i0/architecture1_mult_gen_v12_0_i0.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i96/architecture1_mult_gen_v12_0_i96.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i97/architecture1_mult_gen_v12_0_i97.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i89/architecture1_mult_gen_v12_0_i89.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i82/architecture1_mult_gen_v12_0_i82.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i93/architecture1_mult_gen_v12_0_i93.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i99/architecture1_mult_gen_v12_0_i99.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i90/architecture1_mult_gen_v12_0_i90.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i86/architecture1_mult_gen_v12_0_i86.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i84/architecture1_mult_gen_v12_0_i84.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i79/architecture1_mult_gen_v12_0_i79.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i87/architecture1_mult_gen_v12_0_i87.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i92/architecture1_mult_gen_v12_0_i92.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i94/architecture1_mult_gen_v12_0_i94.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i85/architecture1_mult_gen_v12_0_i85.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i81/architecture1_mult_gen_v12_0_i81.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i88/architecture1_mult_gen_v12_0_i88.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i91/architecture1_mult_gen_v12_0_i91.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i95/architecture1_mult_gen_v12_0_i95.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i80/architecture1_mult_gen_v12_0_i80.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i98/architecture1_mult_gen_v12_0_i98.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i83/architecture1_mult_gen_v12_0_i83.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i103/architecture1_mult_gen_v12_0_i103.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i101/architecture1_mult_gen_v12_0_i101.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i102/architecture1_mult_gen_v12_0_i102.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i100/architecture1_mult_gen_v12_0_i100.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i7/architecture1_mult_gen_v12_0_i7.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i8/architecture1_mult_gen_v12_0_i8.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i10/architecture1_mult_gen_v12_0_i10.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i14/architecture1_mult_gen_v12_0_i14.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i5/architecture1_mult_gen_v12_0_i5.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i6/architecture1_mult_gen_v12_0_i6.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i15/architecture1_mult_gen_v12_0_i15.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i12/architecture1_mult_gen_v12_0_i12.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i41/architecture1_mult_gen_v12_0_i41.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i16/architecture1_mult_gen_v12_0_i16.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i13/architecture1_mult_gen_v12_0_i13.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i11/architecture1_mult_gen_v12_0_i11.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i9/architecture1_mult_gen_v12_0_i9.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i70/architecture1_mult_gen_v12_0_i70.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i68/architecture1_mult_gen_v12_0_i68.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i72/architecture1_mult_gen_v12_0_i72.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i67/architecture1_mult_gen_v12_0_i67.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i73/architecture1_mult_gen_v12_0_i73.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i75/architecture1_mult_gen_v12_0_i75.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i74/architecture1_mult_gen_v12_0_i74.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i66/architecture1_mult_gen_v12_0_i66.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i71/architecture1_mult_gen_v12_0_i71.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i76/architecture1_mult_gen_v12_0_i76.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i77/architecture1_mult_gen_v12_0_i77.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i78/architecture1_mult_gen_v12_0_i78.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i69/architecture1_mult_gen_v12_0_i69.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i47/architecture1_mult_gen_v12_0_i47.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i48/architecture1_mult_gen_v12_0_i48.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i44/architecture1_mult_gen_v12_0_i44.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i46/architecture1_mult_gen_v12_0_i46.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i49/architecture1_mult_gen_v12_0_i49.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i52/architecture1_mult_gen_v12_0_i52.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i45/architecture1_mult_gen_v12_0_i45.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i53/architecture1_mult_gen_v12_0_i53.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i51/architecture1_mult_gen_v12_0_i51.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i50/architecture1_mult_gen_v12_0_i50.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i42/architecture1_mult_gen_v12_0_i42.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i43/architecture1_mult_gen_v12_0_i43.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i64/architecture1_mult_gen_v12_0_i64.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i65/architecture1_mult_gen_v12_0_i65.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i59/architecture1_mult_gen_v12_0_i59.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i56/architecture1_mult_gen_v12_0_i56.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i54/architecture1_mult_gen_v12_0_i54.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i61/architecture1_mult_gen_v12_0_i61.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i62/architecture1_mult_gen_v12_0_i62.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i63/architecture1_mult_gen_v12_0_i63.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i58/architecture1_mult_gen_v12_0_i58.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i55/architecture1_mult_gen_v12_0_i55.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i57/architecture1_mult_gen_v12_0_i57.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i60/architecture1_mult_gen_v12_0_i60.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i37/architecture1_mult_gen_v12_0_i37.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i29/architecture1_mult_gen_v12_0_i29.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i34/architecture1_mult_gen_v12_0_i34.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i36/architecture1_mult_gen_v12_0_i36.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i38/architecture1_mult_gen_v12_0_i38.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i39/architecture1_mult_gen_v12_0_i39.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i31/architecture1_mult_gen_v12_0_i31.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i35/architecture1_mult_gen_v12_0_i35.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i32/architecture1_mult_gen_v12_0_i32.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i33/architecture1_mult_gen_v12_0_i33.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i40/architecture1_mult_gen_v12_0_i40.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i30/architecture1_mult_gen_v12_0_i30.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i17/architecture1_mult_gen_v12_0_i17.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i18/architecture1_mult_gen_v12_0_i18.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i23/architecture1_mult_gen_v12_0_i23.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i24/architecture1_mult_gen_v12_0_i24.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i20/architecture1_mult_gen_v12_0_i20.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i26/architecture1_mult_gen_v12_0_i26.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i22/architecture1_mult_gen_v12_0_i22.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i19/architecture1_mult_gen_v12_0_i19.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i25/architecture1_mult_gen_v12_0_i25.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i27/architecture1_mult_gen_v12_0_i27.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i21/architecture1_mult_gen_v12_0_i21.xci

read_ip -quiet c:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/sources_1/ip/architecture1_mult_gen_v12_0_i28/architecture1_mult_gen_v12_0_i28.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/constrs_1/imports/sysgen/architecture1_clock.xdc
set_property used_in_implementation false [get_files C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/constrs_1/imports/sysgen/architecture1_clock.xdc]

read_xdc C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/constrs_1/imports/sysgen/architecture1.xdc
set_property used_in_implementation false [get_files C:/Users/s4533087/CSSE4010/project/netlist/hdl_netlist/architecture1.srcs/constrs_1/imports/sysgen/architecture1.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top architecture1 -part xc7v2000tflg1925-1 -mode out_of_context
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef architecture1.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file architecture1_utilization_synth.rpt -pb architecture1_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
